// <auto-generated />
using System;
using DanceStudio.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DanceStudio.API.Migrations
{
    [DbContext(typeof(DanceStudioDbContext))]
    partial class DanceStudioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DanceStudio.API.Models.BookingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DanceStudio.API.Models.ClassSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("integer");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudioRoom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSlots = 15,
                            ClassName = "Dance Fitness (Any Age)",
                            Day = "Monday",
                            Instructor = "Ethos Master Team",
                            Level = "All Ages",
                            StudioRoom = "Studio A",
                            Style = "Morning Fitness",
                            Time = "07:30 AM - 08:30 AM",
                            TotalSlots = 25
                        },
                        new
                        {
                            Id = 2,
                            AvailableSlots = 12,
                            ClassName = "Adults Batch (Beginner)",
                            Day = "Monday",
                            Instructor = "Ethos Choreographer",
                            Level = "Beginner",
                            StudioRoom = "Studio A",
                            Style = "Adults Beginner",
                            Time = "09:00 AM - 10:00 AM",
                            TotalSlots = 20
                        },
                        new
                        {
                            Id = 3,
                            AvailableSlots = 10,
                            ClassName = "Kids Batch (4-6 Years)",
                            Day = "Monday",
                            Instructor = "Ethos Kids Lead",
                            Level = "Ages 4-6",
                            StudioRoom = "Studio B",
                            Style = "Kids Batch",
                            Time = "05:00 PM - 06:00 PM",
                            TotalSlots = 15
                        },
                        new
                        {
                            Id = 4,
                            AvailableSlots = 8,
                            ClassName = "Adults Batch (Beginner)",
                            Day = "Monday",
                            Instructor = "Ethos Choreographer",
                            Level = "Beginner",
                            StudioRoom = "Studio A",
                            Style = "Adults Evening",
                            Time = "06:00 PM - 07:00 PM",
                            TotalSlots = 20
                        },
                        new
                        {
                            Id = 5,
                            AvailableSlots = 10,
                            ClassName = "Kids Batch (6-12 Years)",
                            Day = "Monday",
                            Instructor = "Ethos Kids Lead",
                            Level = "Ages 6-12",
                            StudioRoom = "Studio B",
                            Style = "Kids Batch",
                            Time = "07:00 PM - 08:00 PM",
                            TotalSlots = 20
                        },
                        new
                        {
                            Id = 6,
                            AvailableSlots = 6,
                            ClassName = "Adults Batch (Advanced)",
                            Day = "Monday",
                            Instructor = "Ethos Master Director",
                            Level = "Advanced",
                            StudioRoom = "Studio A",
                            Style = "Adults Advanced",
                            Time = "08:00 PM - 09:00 PM",
                            TotalSlots = 15
                        });
                });

            modelBuilder.Entity("DanceStudio.API.Models.CustomerPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CustomerPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiryDate = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            PackageId = 3,
                            PackageName = "Royal Celebration / Monthly Pass",
                            StartDate = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 1025
                        });
                });

            modelBuilder.Entity("DanceStudio.API.Models.DanceClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerSession")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Morning Batch",
                            Description = "High-energy rhythm fitness, cardio jam & sweat workout for all age groups.",
                            Duration = "60 mins",
                            ImageUrl = "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?auto=format&fit=crop&w=800&q=80",
                            Instructor = "Ethos Master Team",
                            Level = "All Ages",
                            PricePerSession = 2500m,
                            Rating = 5.0,
                            Title = "Dance Fitness (Any Age)"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Adults",
                            Description = "Foundation grooves, isolations, swag, and step-by-step Bollywood & Commercial routines.",
                            Duration = "60 mins",
                            ImageUrl = "https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=800&q=80",
                            Instructor = "Ethos Senior Choreographer",
                            Level = "Beginner",
                            PricePerSession = 2500m,
                            Rating = 4.9000000000000004,
                            Title = "Adults Batch (Beginner)"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Kids",
                            Description = "Fun, playful movement, basic rhythm building, and creative balance training for little stars.",
                            Duration = "60 mins",
                            ImageUrl = "https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?auto=format&fit=crop&w=800&q=80",
                            Instructor = "Ethos Kids Lead",
                            Level = "Beginner (Ages 4-6)",
                            PricePerSession = 2000m,
                            Rating = 5.0,
                            Title = "Kids Batch (4-6 Years)"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Kids",
                            Description = "Dynamic dance choreography, stage presentation, and beat coordination for growing dancers.",
                            Duration = "60 mins",
                            ImageUrl = "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=800&q=80",
                            Instructor = "Ethos Kids Lead",
                            Level = "Intermediate (Ages 6-12)",
                            PricePerSession = 2000m,
                            Rating = 4.9000000000000004,
                            Title = "Kids Batch (6-12 Years)"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Adults",
                            Description = "Complex musicality, fast-paced choreography, execution, and performance attitude.",
                            Duration = "60 mins",
                            ImageUrl = "https://images.unsplash.com/photo-1535525153412-5a42439e210d?auto=format&fit=crop&w=800&q=80",
                            Instructor = "Ethos Master Director",
                            Level = "Advanced",
                            PricePerSession = 2500m,
                            Rating = 5.0,
                            Title = "Adults Batch (Advanced)"
                        });
                });

            modelBuilder.Entity("DanceStudio.API.Models.DancePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CTA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingCycle = "1 Session",
                            CTA = "Book Free Demo",
                            FeaturesJson = "[\"Monday - Friday Free Demo Trial\", \"Valid for any 1 batch session\", \"Studio locker access\", \"100% Free - No charges\"]",
                            IsPopular = false,
                            Price = 0m,
                            Title = "Free Demo Trial Pass",
                            Type = "Free Trial"
                        },
                        new
                        {
                            Id = 2,
                            BillingCycle = "Month",
                            CTA = "Join Kids Batch",
                            FeaturesJson = "[\"Mon - Fri Kids Batches\", \"Choice of 4-6 Yrs or 6-12 Yrs slot\", \"Stage performance showcase\", \"Regular progress feedback\"]",
                            IsPopular = false,
                            Price = 2000m,
                            Title = "Kids Monthly Membership (4-12 Yrs)",
                            Type = "Kids Monthly Pass"
                        },
                        new
                        {
                            Id = 3,
                            BillingCycle = "Month",
                            CTA = "Join Adults Batch",
                            FeaturesJson = "[\"Mon - Fri Regular Classes\", \"Dance Fitness / Beginner / Advanced\", \"Choice of Morning or Evening Slot\", \"1 Free Demo Trial included\"]",
                            IsPopular = true,
                            Price = 2500m,
                            Title = "Adults / Fitness Monthly Pass",
                            Type = "Adults Monthly Pass"
                        });
                });

            modelBuilder.Entity("DanceStudio.API.Models.EventWorkshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DanceStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestChoreographer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SeatsLeft")
                        .HasColumnType("integer");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("DanceStudio.API.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstagramHandle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Professional directors bringing high energy training to Kukatpally, Hyderabad.",
                            ImageUrl = "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80",
                            InstagramHandle = "@ethosdancestudio",
                            Name = "Ethos Master Team",
                            Role = "Founder & Choreography Directors",
                            Specialty = "Dance Fitness, Commercial Hip-Hop & Sangeet",
                            YearsExperience = 10
                        });
                });

            modelBuilder.Entity("DanceStudio.API.Models.NotificationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DanceStudio.API.Models.OtpVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("DanceStudio.API.Models.PaymentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RazorpayOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazorpayPaymentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazorpaySignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PaymentRecords");
                });

            modelBuilder.Entity("DanceStudio.API.Models.StudioSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "RazorpayKeyId",
                            Value = "rzp_test_RhythmPulse2025"
                        },
                        new
                        {
                            Id = 2,
                            Key = "RazorpayKeySecret",
                            Value = "Secret_Demo_Key_9981"
                        },
                        new
                        {
                            Id = 3,
                            Key = "AdminUsername",
                            Value = "admin"
                        },
                        new
                        {
                            Id = 4,
                            Key = "AdminPassword",
                            Value = "adminpass"
                        },
                        new
                        {
                            Id = 5,
                            Key = "AdminPhone",
                            Value = "+91 9876543210"
                        });
                });

            modelBuilder.Entity("DanceStudio.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1025,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerCode = "ETH1025",
                            Email = "shanmuka@gmail.com",
                            IsActive = true,
                            Name = "Shanmuka Gaddam",
                            PasswordHash = "ethos123",
                            Phone = "9876543210",
                            Role = "Student"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
