import React from 'react';
import ethosPureLogo from '../assets/ethos_pure_logo.png';
import Footer from '../components/Footer';
import FloatingWhatsApp from '../components/FloatingWhatsApp';
import { ArrowLeft, ArrowRight } from 'lucide-react';

export default function TermsConditionsPage() {
  return (
    <div className="min-h-screen bg-[#FAF8F5] text-slate-900 font-sans">
      
      {/* Top Sticky Bar (Matching img 3) */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-40 px-4 sm:px-8 py-4 flex items-center justify-between shadow-2xs">
        <a
          href="index.html"
          className="text-xs font-black uppercase text-slate-700 hover:text-slate-900 flex items-center gap-1.5 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Home</span>
        </a>

        <a
          href="refund.html"
          className="text-xs font-black uppercase text-slate-700 hover:text-slate-900 flex items-center gap-1.5 transition-colors"
        >
          <span>Cancellation and Refund Policy</span>
          <ArrowRight className="w-4 h-4" />
        </a>
      </header>

      <main className="max-w-5xl mx-auto px-4 sm:px-8 py-12">
        
        {/* White Document Container (Matching img 3) */}
        <div className="bg-white border border-slate-200 rounded-[2.5rem] p-8 sm:p-16 shadow-xl space-y-8 text-left">
          
          {/* Logo & Headline Header (Matching img 3) */}
          <div className="text-center space-y-4 border-b border-slate-100 pb-10">
            <img
              src={ethosPureLogo}
              alt="Ethos Dance Studio"
              className="h-16 w-auto mx-auto object-contain filter drop-shadow-md"
            />
            <h1 className="text-4xl sm:text-6xl font-serif italic text-[#0066CC] font-normal tracking-tight">
              Terms and Conditions
            </h1>
          </div>

          {/* Electronic Record Statement */}
          <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-normal">
            <strong className="text-slate-900">This document is an electronic record</strong> in terms of the <em className="text-slate-800">Information Technology Act, 2000</em> and <em className="text-slate-800">Rule 3 of the Information Technology (Intermediaries guidelines) Rules, 2011</em> and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>

          <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-normal">
            This ETHOS USER Agreement ("T&C") applies to anyone’s use and access of our websites [ethosdancestudio.com] / webpages, emails, WhatsApp groups and other online products and services offered by ETHOS (collectively, the "Services") and our affiliates ("ETHOS," "we," "us," or "our"). We are thrilled to welcome you to ETHOS, an innovative community-building dance space designed to bring individuals with shared interests together. Before you embark on this exciting journey of connection and choreography, we invite you to familiarize yourself with our Terms and Conditions of Use.
          </p>

          {/* Acceptance of Terms */}
          <div className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-black font-syne text-slate-900">
              Acceptance of Terms:
            </h2>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-normal">
              By accessing (or even merely visiting) any part of the ETHOS website, you signify your <strong className="text-slate-900">agreement to comply with and be bound by these Terms and Conditions</strong> and other policies of the Company as posted on the application or website from time to time. If you do not agree with any part of these terms, we kindly request that you refrain from using our platform.
            </p>
          </div>

          {/* Community Values */}
          <div className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-black font-syne text-slate-900">
              Community Values:
            </h2>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-normal">
              ETHOS is dedicated to fostering a <strong className="text-slate-900">positive and inclusive environment</strong>. We encourage users to <strong className="text-slate-900">engage respectfully</strong>, promote <strong className="text-slate-900">diversity</strong>, and contribute to the overall <strong className="text-slate-900">well-being</strong> of the community. Any content that goes against these values may result in appropriate action, including <strong className="text-slate-900">account suspension</strong> or revocation of studio pass access.
            </p>
          </div>

          {/* Privacy Matters */}
          <div className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-black font-syne text-slate-900">
              Privacy Matters:
            </h2>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-normal">
              Your <strong className="text-slate-900">privacy</strong> is paramount to us. Our <strong className="text-slate-900">Privacy Policy</strong> outlines the <strong className="text-slate-900">collection, use, and protection</strong> of your personal information. Please take a moment to review this document and our privacy policy on <a href="privacy.html" className="text-[#0088FF] underline font-bold">privacy.html</a> to understand how your data is handled within the ETHOS platform.
            </p>
          </div>

          {/* Studio Rules */}
          <div className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-black font-syne text-slate-900">
              Studio & Class Regulations:
            </h2>
            <ul className="list-disc pl-5 space-y-2 text-xs sm:text-sm text-slate-600 font-normal">
              <li>Clean indoor footwear or bare feet required inside wooden dance floors.</li>
              <li>Students must arrive 10 minutes prior to scheduled batch times for warm-up safety.</li>
              <li>Monthly class passes are non-transferable unless authorized by studio management.</li>
            </ul>
          </div>

        </div>

      </main>

      <Footer />
      <FloatingWhatsApp />
    </div>
  );
}
